# Generated by Django 4.2.7 on 2023-12-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('prdid', models.IntegerField(primary_key=True, serialize=False)),
                ('prdname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('prdid', models.IntegerField(primary_key=True, serialize=False)),
                ('prdname', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('base2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritapp.base2')),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
            bases=('inheritapp.base2',),
        ),
        migrations.CreateModel(
            name='ProxyPost',
            fields=[
            ],
            options={
                'ordering': ['title'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inheritapp.post',),
        ),
    ]
